"""Generic CENT hardware, instruction, program, and serialization types."""

from .aim import (
    AIM_SIMULATOR_BANKS,
    AIM_SIMULATOR_BURST_LENGTH,
    AIM_SIMULATOR_CHANNELS,
    AimSimulatorCompatibilityError,
    render_aim_channel_mask,
    render_aim_instruction,
    render_aim_trace,
    validate_aim_hardware,
)
from .builder import CentProgramBuilder
from .hardware import BANKS_PER_PU, CentBlockPlacementSpec, CentHardwareSpec
from .instructions import (
    Accumulate,
    ApplyActivation,
    BroadcastCxl,
    CentChannelSet,
    CentInstruction,
    CentMemoryAddress,
    CentOpcode,
    CentSharedBufferAddress,
    CopyBankToGlobalBuffer,
    CopyGlobalBufferToBank,
    ElementwiseMultiply,
    Exponent,
    MacAllBanks,
    MacOperandSource,
    ReadActivation,
    ReadMac,
    ReadSingleBank,
    ReceiveCxl,
    Reduction,
    RunRiscV,
    SendCxl,
    WriteAllBanks,
    WriteBias,
    WriteGlobalBuffer,
    WriteSingleBank,
)
from .program import CentProgram
from .render import render_instruction, render_text_program
from .utils import ceil_div

__all__ = [
    "AIM_SIMULATOR_BANKS",
    "AIM_SIMULATOR_BURST_LENGTH",
    "AIM_SIMULATOR_CHANNELS",
    "BANKS_PER_PU",
    "Accumulate",
    "AimSimulatorCompatibilityError",
    "ApplyActivation",
    "BroadcastCxl",
    "CentBlockPlacementSpec",
    "CentChannelSet",
    "CentHardwareSpec",
    "CentInstruction",
    "CentMemoryAddress",
    "CentOpcode",
    "CentProgram",
    "CentProgramBuilder",
    "CentSharedBufferAddress",
    "CopyBankToGlobalBuffer",
    "CopyGlobalBufferToBank",
    "ElementwiseMultiply",
    "Exponent",
    "MacAllBanks",
    "MacOperandSource",
    "ReadActivation",
    "ReadMac",
    "ReadSingleBank",
    "ReceiveCxl",
    "Reduction",
    "RunRiscV",
    "SendCxl",
    "WriteAllBanks",
    "WriteBias",
    "WriteGlobalBuffer",
    "WriteSingleBank",
    "ceil_div",
    "render_aim_channel_mask",
    "render_aim_instruction",
    "render_aim_trace",
    "render_instruction",
    "render_text_program",
    "validate_aim_hardware",
]
